# -*- coding: utf-8 -*-
music_list = [
    [
        "밀랍천사",
        "파애(破愛)",
        "일탈",
        "욕",
        "격주 코믹스",
        "안녕, 미미",
        "애인발견!!!",
        "이틀전에 죽은 그녀와의 채팅은",
        "어른 아이",
        "마론인형",
        "예뻐",
        "VIOLent VioLEt"
        ],
    [
        "戀人 3/3",
        "미안해 널 미워해",
        "金家萬歲",
        "落花",
        "戀人 2/3 Lover",
        "동두천 Charlie",
        "이런데서 주무시면 얼어죽어요",
        "그래 제길 나 이렇게 살았어",
        "숨은 그림 찾기",
        "戀人 1/3 Queen",
        "하늘로 가는 상자",
        "아파",
        "알아",
        "戀人 3/3 Angel"
        ],
    [
        "미쓰코리아",
        "매직 카펫 라이드",
        "뱀",
        "새",
        "오렌지 마말레이드",
        "Summerday Blues",
        "www.사이버 디지탈.com",
        "꿈의 택배편",
        "벌레",
        "그녀와 단둘이",
        "赤淚",
        "마왕"
        ],
    [
        "#1",
        "우리를 위해 기도해 주세요",
        "Hey Guyz",
        "Vlad",
        "Good Morning",
        "벨벳소로우",
        "팬이야",
        "르샤마지끄",
        "수사반장",
        "Only One",
        "望鄕",
        "無言歌"   
        ],
    [
        "Luv Pill",
        "하하하쏭",
        "사랑의 병원으로 놀러 오세요",
        "I Saw Him",
        "거지",
        "曠野",
        "우리에게 내일은 없다",
        "惡夢",
        "실리콘벨리",
        "파트너",
        "17171771",
        "Social Life",
        "Truth"
        ],
    [
        "Seoul Blues",
        "Loving Memory",
        "Jester Song",
        "You And Me",
        "Summer Slumber",
        "죽은 자들의 무도회",
        "Beautiful Girl",
        "Over And Over Again I Think Of You",
        "6월 이야기",
        "위로",
        "Old Man",
        "Blue Devils",
        "Good Boy",
        "Oh, Mama!",
        "샤이닝"
        ],
    [
        "Oh, Honey!",
        "幸福한 王子",
        "Something Good",
        "Drops",
        "20세기 소년소녀",
        "반딧불",
        "Carnival Amour",
        "Love Rock'n Roll",
        "27",
        "옛날",
        "the DEVIL",
        "poor tom",
        "blue marble"
        ],
    [
        "HAPPY DAY",
        "IDOL",
        "EV1",
        "꿈에",
        "PEEP SHOW",
        "RED RAIN",
        "혼자가 아니야",
        "誻誻",
        "from:me@iwaswrong.com to:you@aremy.net",
        "피터의 노래",
        "snowdrop"
        ],
    [
        "Anna",
        "Dear Mother",
        "님아",
        "템페스트",
        "I feel good",
        "스물다섯, 스물하나",
        "무지개",
        "Dancing star",
        "전하고 싶은 말",
        "이카루스",
        "슬픔이여 이제 안녕"
        ],
]
